apiVersion: v1
kind: Pod 
metadata: 
  name: cart-app-pod
  namespace: rashmi-ns
spec: 
  containers: 
    - name: test-container
      image: rashmi47/sre-test-image:1.0
      ports:
        - containerPort: 3015